name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish to packagist.org
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: "${{ vars.packagist_username }}"
          api_token: ${{ secrets.packagist_api_token }}
